### ISSUE TITLE
能不能把YYModel等库都一起上传上来 pod很慢

### ISSUE THREAD

**Issue by CoderTonyChan** [wsl2ls/iOS_Tips#17]
能不能把YYModel等库都一起上传上来 pod很慢

**Comment by wsl2ls** [comment]
> 能不能把YYModel等库都一起上传上来 pod很慢

@CoderTonyChan pod库传上去的话，这个仓库就变大了，下载会慢的，pod不要着急，慢慢pod😀

**Comment by CoderTonyChan** [comment]
> > 能不能把YYModel等库都一起上传上来 pod很慢
> 
> @CoderTonyChan pod库传上去的话，这个仓库就变大了，下载会慢的，pod不要着急，慢慢pod😀

你本来也上传了pod库 但是缺了YYModel 你看看你的git库

**Comment by wsl2ls** [comment]
@CoderTonyChan 我擦，还真是，我处理一下~只传Podfile

**Comment by CoderTonyChan** [comment]
> @CoderTonyChan 我擦，还真是，我处理一下~只传Podfile

额 能上传一下吗？你现在砍掉git库也不会变小啊 3M不到吧 这几个库
