### ISSUE TITLE
下载两次了都是解压缩错误...文件上传不全?

### ISSUE THREAD

**Issue by SnailLoveSmile** [wsl2ls/iOS_Tips#4]

**Comment by wsl2ls** [comment]
应该是网络问题，我这边下载没问题，用谷歌浏览器试试

发自wsl的 iPhone

**Comment by SnailLoveSmile** [comment]
是的，走本地git clone就比较快了------------------ 原始邮件 ------------------
发件人: "wsl"<notifications@github.com>
发送时间: 2019年11月6日(星期三) 上午9:12
收件人: "wsl2ls/iOS_Tips"<iOS_Tips@noreply.github.com>;
抄送: "ZST"<1016483779@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [wsl2ls/iOS_Tips] 下载两次了都是解压缩错误...文件上传不全? (#4)


应该是网络问题，我这边下载没问题，用谷歌浏览器试试
 
 发自wsl的 iPhone
 
 > 在 2019年11月6日，09:06，ZST <notifications@github.com> 写道：
 > 
 > &#xFEFF;
 > Closed #4.
 > 
 > —
 > You are receiving this because you are subscribed to this thread.
 > Reply to this email directly, view it on GitHub, or unsubscribe.
 
&mdash;
