### ISSUE TITLE
我放到我项目的公共库里面去一直报Undefined symbols

### ISSUE THREAD

**Issue by YonGang** [wsl2ls/iOS_Tips#9]
![image](https://user-images.githubusercontent.com/20411138/74902664-ae957980-53e1-11ea-99e3-6bbb7e39f5bd.png)

**Comment by wsl2ls** [comment]
@YonGang 是不是这个WebP.framework没有添加到项目里呀？
<img width="709" alt="屏幕快照 2020-02-20 下午2 29 09" src="https://user-images.githubusercontent.com/15356122/74906954-5e241900-53ed-11ea-80a9-6e1a21cbc093.png">
